// ==============================================================================
// Sync endpoint — receives records from the scan station laptop.
//
// Deployed as a web app that runs as the TEAM account and that anyone can
// reach, so every request must carry SYNC_TOKEN. It only writes; it never
// returns scouting data. It writes Raw (append-only), Teams, Matches,
// Summary and Config, and never touches the Mentor tabs (CLAUDE.md rule).
//
// Config.js (SHEET_ID, SYNC_TOKEN) and Fields.js are generated by
// `npm run dashboard:build` — don't edit them here.
// ==============================================================================

var RAW_META = ['synced_at', 'event', 'match_key', 'match', 'team', 'station', 'scout_id', 'scout_name',
  'scouted_at', 'ts', 'app_version', 'schema_version', 'rkey', 'laptop_id'];

function rawHeaders_() {
  return RAW_META.concat(FIELDS.map(function (f) { return f.key; }), ['values_json', 'qr']);
}

/** Connectivity check for the laptop's "Test" button. Returns no data. */
function doGet() {
  return json_({ ok: true, service: 'warlocks-1507-sync' });
}

function doPost(e) {
  var body;
  try { body = JSON.parse(e.postData.contents); } catch (err) { return json_({ ok: false, error: 'Bad JSON' }); }
  if (!body || body.token !== SYNC_TOKEN) return json_({ ok: false, error: 'Bad sync token — re-copy it into the scan station' });
  try {
    return json_(withLock_(function () { return handleSync_(SpreadsheetApp.openById(SHEET_ID), body, new Date()); }));
  } catch (err) {
    return json_({ ok: false, error: String(err && err.message || err) });
  }
}

/** The whole sync, given the spreadsheet. Separate from doPost so tests can drive it. */
function handleSync_(ss, body, now) {
  var event = String(body.event || '');
  if (!/^[a-z0-9]{3,16}$/.test(event)) return { ok: false, error: 'Bad event code' };
  var records = body.records || [];

  // Tabs the sync owns: create once, protect so mentors can't edit them by accident.
  var raw = getOrCreateSheet_(ss, TAB.RAW);
  var headers = ensureHeaderColumns_(raw, rawHeaders_());
  protectOwnerOnly_(raw, 'Scouting data — written only by the sync. Never edit.');
  [TAB.SUMMARY, TAB.TEAMS, TAB.MATCHES].forEach(function (name) {
    protectOwnerOnly_(getOrCreateSheet_(ss, name), 'Written by the sync — edits would be overwritten.');
  });
  [TAB.MENTOR, TAB.PRIVATE].forEach(function (name, i) {
    ensureHeaderColumns_(getOrCreateSheet_(ss, name), i ? PRIVATE_HEADERS : MENTOR_HEADERS);
  });

  // 1. Append records we don't have yet (the QR text identifies an exact record version).
  var idx = headerIndex_(headers);
  var existing = {};
  readRows_(raw).forEach(function (r) { existing[r[idx.qr]] = true; });
  var fieldsByKey = {};
  FIELDS.forEach(function (f) { fieldsByKey[f.key] = f; });
  var stamp = now.toISOString();
  var newRows = [];
  records.forEach(function (r) {
    if (!r || !r.qr || existing[r.qr]) return;
    existing[r.qr] = true;
    var row = headers.map(function () { return ''; });
    var put = function (k, v) { if (idx[k] !== undefined) row[idx[k]] = cellText_(v); };
    put('synced_at', stamp); put('event', r.event); put('match_key', r.match_key); put('match', matchLabel_(r.match_key));
    put('team', r.team); put('station', r.station); put('scout_id', r.scout_id); put('scout_name', r.scout_name || '');
    put('scouted_at', new Date(r.ts * 1000).toISOString()); put('ts', r.ts); put('app_version', r.app_version);
    put('schema_version', r.schema_version); put('rkey', r.rkey); put('laptop_id', r.id);
    Object.keys(r.values || {}).forEach(function (k) {
      if (fieldsByKey[k]) put(k, displayField_(fieldsByKey[k], r.values[k]));
    });
    put('values_json', JSON.stringify(r.values || {}));
    put('qr', r.qr);
    newRows.push(row);
  });
  if (newRows.length) raw.getRange(raw.getLastRow() + 1, 1, newRows.length, headers.length).setValues(newRows);

  // 2. Teams and schedule, when the laptop sends them (only after they change).
  if (body.teams) {
    writeTable_(getOrCreateSheet_(ss, TAB.TEAMS), ['team_number', 'team_name'],
      body.teams.map(function (t) { return [t.team, cellText_(t.name || '')]; }));
  }
  if (body.schedule) {
    writeTable_(getOrCreateSheet_(ss, TAB.MATCHES), ['match_key', 'match', 'red1', 'red2', 'red3', 'blue1', 'blue2', 'blue3'],
      body.schedule.map(function (m) { return [m.key, matchLabel_(m.key)].concat(m.teams); }));
  }

  // 3. Rebuild the Summary from every current record for this event.
  var all = readRows_(raw).filter(function (r) { return r[idx.event] === event; }).map(function (r) {
    var values = {};
    try { values = JSON.parse(r[idx.values_json] || '{}'); } catch (e) { /* skip bad row */ }
    return { event: r[idx.event], rkey: r[idx.rkey], ts: Number(r[idx.ts]), laptop_id: Number(r[idx.laptop_id]),
      team: Number(r[idx.team]), match_key: r[idx.match_key], scout_id: r[idx.scout_id], values: values };
  });
  var names = {};
  readObjects_(getOrCreateSheet_(ss, TAB.TEAMS)).forEach(function (t) { names[t.team_number] = t.team_name; });
  var summary = summarizeTeams(currentRecords_(all), names);
  writeTable_(getOrCreateSheet_(ss, TAB.SUMMARY), SUMMARY_COLUMNS,
    summary.map(function (t) { return summaryToRow_(t).map(cellText_); }));

  // 4. Freshness for the dashboard's "Synced N min ago".
  kvSet_(ss, 'last_sync_ms', now.getTime());
  kvSet_(ss, 'event', event);
  if (body.eventName) kvSet_(ss, 'event_name', body.eventName);
  kvSet_(ss, 'records_total', all.length);

  return {
    ok: true,
    accepted: records.map(function (r) { return r && r.id; }).filter(function (id) { return id !== undefined; }),
    added: newRows.length,
    total: all.length,
    teams: summary.length,
  };
}

/** Human-readable value for the Raw tab (the exact values are in values_json). */
function displayField_(f, v) {
  if (f.type === 'bool') return v ? 'TRUE' : 'FALSE';
  if (f.type === 'enum') return v === null || v === undefined ? '' : f.options[v];
  if (f.type === 'multi') return f.options.filter(function (_, i) { return v & (1 << i); }).join(', ');
  if (f.type === 'rating') return v === null || v === undefined ? '' : v;
  return v === null || v === undefined ? '' : v;
}
