// ==============================================================================
// Builds and deploys the two Apps Script projects with clasp.
//
//   npm run dashboard:create   one time: creates the scouting Sheet + both projects
//   npm run dashboard:build    assembles dashboard/build/<project>/ (no Google needed)
//   npm run dashboard:push     build + upload + deploy (keeps the same web app URLs)
//
// Needs clasp installed and logged in as the TEAM account:
//   npm install -g @google/clasp   then   clasp login
//
// Secrets and IDs live in data/dashboard.json (gitignored): Sheet ID, script
// IDs, deployment IDs and the sync token. The scan station reads that file too,
// so the sync URL and token never need copying by hand on this laptop.
// ==============================================================================

import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { join, resolve } from 'node:path';

import { FIELDS, SCHEMA_VERSION } from '../shared/fields.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DASH = join(ROOT, 'dashboard');
const BUILD = join(DASH, 'build');
const DATA = process.env.SCOUT_DATA || join(ROOT, 'data');
const STATE_FILE = join(DATA, 'dashboard.json');
const PROJECTS = {
  web: { title: 'Warlocks 1507 Pick List', type: 'sheets' },
  'sync-endpoint': { title: 'Warlocks 1507 Sync Endpoint', type: 'standalone' },
};

const readState = () => (existsSync(STATE_FILE) ? JSON.parse(readFileSync(STATE_FILE, 'utf8')) : {});
function writeState(s) {
  mkdirSync(DATA, { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(s, null, 2));
}

function clasp(args, cwd) {
  const res = spawnSync('clasp', args, { cwd, shell: true, encoding: 'utf8' });
  const out = `${res.stdout || ''}${res.stderr || ''}`;
  if (res.status !== 0) {
    if (/not recognized|not found|ENOENT/i.test(out) || res.error) {
      throw new Error('clasp is not installed. Run:  npm.cmd install -g @google/clasp   then   clasp.cmd login');
    }
    throw new Error(`clasp ${args.join(' ')} failed:\n${out}`);
  }
  return out;
}

/** Generated copy of shared/fields.js for Apps Script (it can't import ES modules). */
export function fieldsJs() {
  // JSON drops function properties (e.g. `implies`), which the dashboard doesn't need.
  return `// GENERATED by tools/dashboard.js from shared/fields.js — do not edit.\n` +
    `var SCHEMA_VERSION = ${SCHEMA_VERSION};\nvar FIELDS = ${JSON.stringify(FIELDS, null, 2)};\n`;
}

export function build(state = readState()) {
  rmSync(BUILD, { recursive: true, force: true });
  for (const name of Object.keys(PROJECTS)) {
    const out = join(BUILD, name);
    mkdirSync(out, { recursive: true });
    cpSync(join(DASH, 'common'), out, { recursive: true });
    cpSync(join(DASH, name), out, { recursive: true, filter: (src) => !src.endsWith('.clasp.json') });
    writeFileSync(join(out, 'Fields.js'), fieldsJs());
    if (name === 'sync-endpoint') {
      if (!state.sheetId || !state.token) throw new Error('No Sheet yet — run  npm run dashboard:create  first.');
      writeFileSync(join(out, 'Config.js'), '// GENERATED by tools/dashboard.js from data/dashboard.json — do not edit or commit.\n' +
        `var SHEET_ID = ${JSON.stringify(state.sheetId)};\nvar SYNC_TOKEN = ${JSON.stringify(state.token)};\n`);
    }
  }
  console.log(`Built dashboard/build/ (fields schema v${SCHEMA_VERSION})`);
}

function create() {
  const state = readState();
  if (state.sheetId) throw new Error(`Already created (Sheet ${state.sheetId}). Delete data/dashboard.json to start over.`);
  for (const [name, p] of Object.entries(PROJECTS)) {
    const dir = join(DASH, name);
    const claspFile = join(dir, '.clasp.json');
    if (existsSync(claspFile)) rmSync(claspFile);
    console.log(`Creating ${p.title}…`);
    console.log(clasp(['create-script', '--type', p.type, '--title', `"${p.title}"`, '--rootDir', `../build/${name}`], dir));
    const cfg = JSON.parse(readFileSync(claspFile, 'utf8'));
    state[name] = { scriptId: cfg.scriptId };
    if (name === 'web') {
      state.sheetId = (Array.isArray(cfg.parentId) ? cfg.parentId[0] : cfg.parentId) || null;
      if (!state.sheetId) throw new Error(`clasp didn't report the new Sheet's ID. .clasp.json was:\n${JSON.stringify(cfg)}`);
    }
  }
  state.token = randomBytes(24).toString('base64url');
  writeState(state);
  console.log(`\nSheet: https://docs.google.com/spreadsheets/d/${state.sheetId}/edit`);
  console.log('Saved IDs and the sync token to data/dashboard.json (never commit it).');
  console.log('Next:  npm run dashboard:push');
}

function push() {
  const state = readState();
  build(state);
  for (const name of Object.keys(PROJECTS)) {
    const dir = join(DASH, name);
    if (!existsSync(join(dir, '.clasp.json'))) throw new Error(`dashboard/${name}/.clasp.json missing — run  npm run dashboard:create`);
    console.log(`Pushing ${name}…`);
    clasp(['push', '--force'], dir);
    const desc = `"${new Date().toISOString().slice(0, 16)}"`;
    const existing = state[name].deploymentId;
    const out = existing
      ? clasp(['update-deployment', existing, '--description', desc], dir)
      : clasp(['create-deployment', '--description', desc], dir);
    const id = existing || (out.match(/AKfy[\w-]+/) || [])[0];
    if (!id) throw new Error(`Couldn't find the deployment ID in clasp's output:\n${out}`);
    state[name].deploymentId = id;
    state[name].url = `https://script.google.com/macros/s/${id}/exec`;
    writeState(state);
  }
  console.log('\nDone.');
  console.log(`  Mentor dashboard: ${state.web.url}`);
  console.log(`  Sync endpoint:    ${state['sync-endpoint'].url}  (the scan station picks this up automatically)`);
  console.log(`  Sheet:            https://docs.google.com/spreadsheets/d/${state.sheetId}/edit  — share with mentors as Editor`);
}

const cmd = process.argv[2];
const runDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (runDirectly) {
  try {
    if (cmd === 'create') create();
    else if (cmd === 'build') build();
    else if (cmd === 'push') push();
    else console.log('Usage: node tools/dashboard.js create | build | push');
  } catch (err) {
    console.error(`\n✗ ${err.message}`);
    process.exit(1);
  }
}
